baseURL = "https://chollinger.com/blog/"
languageCode = "en-us"
title = "Christian Hollinger"
theme = "ink-free"

copyright = "Â© Christian Hollinger"
[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
  subtitle = "Software Engineering, GNU/Linux, Data, ML, and other things"
  # Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"
  featherIconsCDN = false
  #mode = "dark" # "dark" or "auto"
  toc = true
  # Max tags
  maxTags = 7
  # Define words per minute to approximate reading time
  wpm = 300

  # Stupid footers :)
  footers = [ 
    "What Tiger King can teach us about x86 Assembly", 
    "Running Hadoop on my Thermostat", 
    "How to google Rust and Go Questions and how to skip DIY Blogs",
    "My Potato Salad Recipe on the Cloud",
    "Serverless, Cloud-Native Cooking Recipes",
    "Why this Year will be the Year of the Linux Desktop",
    "Haskell: A 70 Page Essay on why it will be the Next Big Thing - this Time for real!",
    "74 Reasons to Downgrade to Windows ME right now",
    "My Life as CTO: Why you NEED to force people to use the Dvorak layout",
    "Emoji-Driven Programming: Our Startup tried it (and we succeeded)",
    "How I use AI to generate a Feature Matrix for my new SaaS Startup",
    "My Toaster installed Ransomware on my Fridge - Please Help",
    "10 Reasons why gcc SHOULD be re-written in JavaScript - You won't believe #8!",
    "That Pointer isn't unsafe - it's going on an adventure: How to have difficult Engineering Discussions",
    "i = 0x5f3759df - ( i >> 1 ); // what the f...? - How to write clean Code in C",
    "Lean Cloud: Running WordPress in only 7,000 lines of Cloud Formation Templates"
    ]

  # Github base url
  github = "https://github.com/chollinger93/chollinger-blog"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/chollinger93"

[[params.social]]
name = "RSS"
icon = "rss"
url = "index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
